name: carcar_launcher
description: "CarrotPlay - Car Launcher App by kooingh354"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  permission_handler: ^11.0.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.7

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/icon.png"
  branding: "assets/icon.png"
  color_dark: "#000000"
  image_dark: "assets/icon.png"
  branding_dark: "assets/icon.png"
  
  android_12:
    image: "assets/icon.png"
    icon_background_color: "#000000"
    image_dark: "assets/icon.png"
    icon_background_color_dark: "#000000"
  
  web: false

flutter:
  uses-material-design: true
